volumes:
  dbdata:

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: relogin
      MYSQL_USER: relogin
      MYSQL_PASSWORD: relogin
      MYSQL_DATABASE: relogin
    platform: linux/amd64
    volumes:
      - dbdata:/var/lib/mysql
  php:
    depends_on:
      - db
    build: .
    platform: linux/amd64
    volumes:
      - .:/var/www/html
    environment:
      RE_ERROR_REPORTING_SWITCH: errRep
    command: /var/www/html/start.sh
  httpd:
    depends_on:
      - php
    image: itsziget/httpd24:2.0.3
    volumes:
      - .:/var/www/html
    environment:
      SRV_ALLOW_OVERRIDE: "true"
      SRV_DOCROOT: /var/www/html
      SRV_PHP: "true"
      SRV_PHP_HOST: php
      SRV_PHP_TIMEOUT: ${RE_PHP_TIMEOUT:-3600} # 3600 by default for xdebug
    ports:
      - "${RE_PORT:-80}:80"
